# -*- coding: utf-8 -*-
"""TF algo model 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HpgSrGJ4AGwNVIpDk0P3TRFgAZKHgdbB
"""

# Installing necessary packages (Run this once)
!pip install yfinance pandas numpy pandas_ta scikit-learn backtesting requests matplotlib

import yfinance as yf
import pandas as pd
import numpy as np
import pandas_ta as ta
import requests
import io
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from backtesting import Backtest, Strategy
import warnings

# ignoring the warnings
warnings.filterwarnings("ignore")

print("✅ Phase 1: Libraries Installed and Environment Ready.")

def get_nifty500_tickers():
    """
    iam using the  Nifty 500 stocks
    Returns a list of stocks in Yahoo Finance (e.g., 'RELIANCE.NS').
    using the stocks from the link
    """
    try:
        url = "https://nsearchives.nseindia.com/content/indices/ind_nifty500list.csv"
        headers = {'User-Agent': 'Mozilla/5.0'}
        s = requests.get(url, headers=headers, timeout=5).content
        df = pd.read_csv(io.StringIO(s.decode('utf-8')))
        return [t + ".NS" for t in df['Symbol'].tolist()]
    except:
        print("⚠️ NSE Download failed (Blocking). Using Fallback Universe.")
        # Representative sample across sectors
        return [
            'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'ITC.NS',
            'SBIN.NS', 'BHARTIARTL.NS', 'LICI.NS', 'HINDUNILVR.NS', 'TATAMOTORS.NS',
            'LT.NS', 'BAJFINANCE.NS', 'MARUTI.NS', 'SUNPHARMA.NS', 'ADANIENT.NS',
            'TITAN.NS', 'KOTAKBANK.NS', 'ONGC.NS', 'TATASTEEL.NS', 'NTPC.NS',
            'POWERGRID.NS', 'M&M.NS', 'WIPRO.NS', 'ZOMATO.NS', 'DLF.NS', 'HAL.NS',
            'BEL.NS', 'VBL.NS', 'TRENT.NS', 'SIEMENS.NS', 'DMART.NS', 'ABB.NS'
        ]

tickers = get_nifty500_tickers()
print(f"✅ Phase 2: Universe Loaded with {len(tickers)} stocks.")

def add_market_intelligence(data):
    """
    Calculates 15 Technical Indicators for ML Input.
    """
    df = data.copy()

    # --- A. VOLATILITY (Risk Assessment) ---
    # 1. Rolling Volatility (20-day standard deviation)
    df['Volatility'] = df['Close'].pct_change().rolling(20).std()
    # 2. ATR (Average True Range)
    df['ATR'] = ta.atr(df['High'], df['Low'], df['Close'], length=14)
    # 3. Bollinger Band Width (Squeeze detection)
    bb = ta.bbands(df['Close'], length=20, std=2)
    if bb is not None:
        df['BB_Width'] = (bb.iloc[:, 2] - bb.iloc[:, 0]) / bb.iloc[:, 1]

    # --- B. MOMENTUM (Price Velocity) ---
    # 4. RSI (Relative Strength Index)
    df['RSI'] = ta.rsi(df['Close'], length=14)
    # 5. ROC (Rate of Change)
    df['ROC'] = ta.roc(df['Close'], length=10)
    # 6. Williams %R
    df['WillR'] = ta.willr(df['High'], df['Low'], df['Close'], length=14)
    # 7. Stochastic Oscillator %K
    stoch = ta.stoch(df['High'], df['Low'], df['Close'])
    if stoch is not None: df['Stoch_K'] = stoch.iloc[:, 0]
    # 8. CCI (Commodity Channel Index)
    df['CCI'] = ta.cci(df['High'], df['Low'], df['Close'], length=20)

    # --- C. TREND (Direction Strength) ---
    # 9. MACD Line
    macd = ta.macd(df['Close'])
    if macd is not None: df['MACD'] = macd.iloc[:, 0]
    # 10. ADX (Trend Strength)
    adx = ta.adx(df['High'], df['Low'], df['Close'], length=14)
    if adx is not None: df['ADX'] = adx.iloc[:, 0]
    # 11. SMA 50 Distance (Medium term)
    df['Dist_SMA50'] = (df['Close'] / ta.sma(df['Close'], length=50)) - 1
    # 12. SMA 200 Distance (Long term)
    df['Dist_SMA200'] = (df['Close'] / ta.sma(df['Close'], length=200)) - 1
    # 13. Parabolic SAR Distance
    psar = ta.psar(df['High'], df['Low'], df['Close'])
    if psar is not None:
        psar_combined = psar.iloc[:, 0].fillna(0) + psar.iloc[:, 1].fillna(0)
        df['Dist_PSAR'] = (df['Close'] - psar_combined) / df['Close']

    # --- D. VOLUME (Conviction) ---
    # 14. MFI (Money Flow Index)
    df['MFI'] = ta.mfi(df['High'], df['Low'], df['Close'], df['Volume'], length=14)
    # 15. CMF (Chaikin Money Flow)
    df['CMF'] = ta.cmf(df['High'], df['Low'], df['Close'], df['Volume'], length=20)

    return df.dropna()

print("✅ Phase 3: Feature Engineering Module Ready.")

print("--- Phase 4: Training the Brain (ML Model) ---")

# 1. Downloading Training Data Nifty500 stocks
df_train = yf.download('^NSEI', start='2010-01-01', end='2024-01-01', progress=False)
if isinstance(df_train.columns, pd.MultiIndex): df_train.columns = df_train.columns.get_level_values(0)

# 2. Applying Features
df_train = add_market_intelligence(df_train)

# 3. Create Labels (The "Truth")
# Bull (2) = >2.5% return in 20 days
# Bear (0) = <-2.5% return in 20 days
# Sideways (1) = Between -2.5% and 2.5%
df_train['Future_Ret'] = df_train['Close'].shift(-20) / df_train['Close'] - 1
def label_regime(x):
    if x > 0.025: return 2
    elif x < -0.025: return 0
    else: return 1
df_train['Target'] = df_train['Future_Ret'].apply(label_regime)

# 4. Train Model
feature_cols = ['Volatility', 'ATR', 'BB_Width', 'RSI', 'ROC', 'WillR', 'Stoch_K', 'CCI',
                'MACD', 'ADX', 'Dist_SMA50', 'Dist_SMA200', 'Dist_PSAR', 'MFI', 'CMF']

clean_train = df_train.dropna()
rf_model = RandomForestClassifier(n_estimators=200, min_samples_leaf=5, random_state=42, n_jobs=-1)
rf_model.fit(clean_train[feature_cols], clean_train['Target'])

print("✅ Phase 4 Complete: Model Trained on Nifty 50 Index.")

class MLRegimeStrategy(Strategy):
    def init(self):
        # The 'Regime' column is pre-calculated before backtest
        pass

    def next(self):
        # Get today's predicted regime (0=Bear, 1=Sideways, 2=Bull)
        regime = self.data.Regime[-1]

        # --- TRADING LOGIC ---
        if regime == 2: # BULLISH
            if not self.position:
                self.buy() # Enter Long

        elif regime == 0: # BEARISH
            if self.position:
                self.position.close() # Sell/Exit to Cash

        # SIDEWAYS (1): We Hold (Pass)
        # This reduces over-trading and brokerage costs

print("--- Phase 6: Running Backtest on Portfolio ---")

results_list = []
equity_curves = {}

# Iterate through tickers
for ticker in tickers:
    try:
        # 1. Get Data (5 Years)
        data = yf.download(ticker, period="5y", progress=False)
        if isinstance(data.columns, pd.MultiIndex): data.columns = data.columns.get_level_values(0)

        if len(data) < 500: continue

        # 2. Calculate Features
        data = add_market_intelligence(data)

        # 3. AI Prediction (Simulating Historical Decisions)
        # We use the model trained in Phase 4 to predict regimes for this specific stock
        pred_input = data[feature_cols]
        data['Regime'] = rf_model.predict(pred_input)

        # 4. Run Backtest
        bt = Backtest(data, MLRegimeStrategy, cash=100000, commission=0.002)
        stats = bt.run()

        # 5. Store Metrics
        results_list.append({
            'Ticker': ticker,
            'Return': stats['Return [%]'],
            'BuyHold': stats['Buy & Hold Return [%]'],
            'WinRate': stats['Win Rate [%]'],
            'MaxDD': stats['Max. Drawdown [%]'],
            'Trades': stats['# Trades']
        })

        # Store equity curve for visualization
        equity_curves[ticker] = stats['_equity_curve']['Equity']

        print(f"✅ {ticker}: Return {stats['Return [%]:.2f']}% | WinRate {stats['Win Rate [%]:.1f']}%")

    except Exception as e:
        pass

print(f"\n✅ Phase 6 Complete: Tested {len(results_list)} stocks.")

print("\n=== PERFORMANCE REPORT ===")
if results_list:
    df_res = pd.DataFrame(results_list)
    df_res = df_res.replace([np.inf, -np.inf], np.nan).dropna()

    print(f"Average Strategy Return:   {df_res['Return'].mean():.2f}%")
    print(f"Average Buy & Hold Return: {df_res['BuyHold'].mean():.2f}%")
    print(f"Average Win Rate:          {df_res['WinRate'].mean():.2f}%")
    print(f"Average Drawdown:          {df_res['MaxDD'].mean():.2f}%")

    print("\n🏆 TOP 5 PERFORMERS:")
    print(df_res.sort_values(by='Return', ascending=False).head(5)[['Ticker', 'Return', 'WinRate']])
else:
    print("No results generated.")

# Create an aggregate portfolio curve (assuming equal investment in all stocks)
if equity_curves:
    df_equity = pd.DataFrame(equity_curves)
    # Normalize to start at 100
    df_equity = df_equity.apply(lambda x: x / x.iloc[0] * 100)
    # Calculate Average Portfolio Value
    df_equity['Portfolio_Avg'] = df_equity.mean(axis=1)

    plt.figure(figsize=(12, 6))
    plt.plot(df_equity.index, df_equity['Portfolio_Avg'], label='ML Strategy Portfolio', color='blue', linewidth=2)
    plt.title('Strategy Equity Curve (Rebased to 100)', fontsize=14)
    plt.xlabel('Date')
    plt.ylabel('Portfolio Value')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()