# -*- coding: utf-8 -*-
"""TF algo model 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPUTytkxyaOIc_t19sB9yQ7Zgrv9T9ND
"""

# Install required packages
!pip install yfinance pandas numpy pandas_ta scikit-learn backtesting requests

import yfinance as yf
import pandas as pd
import numpy as np
import pandas_ta as ta
import requests
import io
import random
import warnings
from sklearn.ensemble import RandomForestClassifier
from backtesting import Backtest, Strategy

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")
print("✅ Step 1: Environment Setup Complete.")

print("--- STEP 2: DEFINING STOCK UNIVERSE ---")

def get_nifty500_tickers():
    try:
        # Attempt to scrape official NSE list
        url = "https://nsearchives.nseindia.com/content/indices/ind_nifty500list.csv"
        headers = {'User-Agent': 'Mozilla/5.0'}
        s = requests.get(url, headers=headers, timeout=5).content
        df = pd.read_csv(io.StringIO(s.decode('utf-8')))
        return [t + ".NS" for t in df['Symbol'].tolist()]
    except:
        print("⚠️ NSE Download failed. Using fallback Nifty list.")
        # Fallback list of major stocks across sectors
        return [
            'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'ITC.NS', 'SBIN.NS',
            'BHARTIARTL.NS', 'LICI.NS', 'HINDUNILVR.NS', 'TATAMOTORS.NS', 'LT.NS', 'BAJFINANCE.NS',
            'MARUTI.NS', 'SUNPHARMA.NS', 'ADANIENT.NS', 'TITAN.NS', 'KOTAKBANK.NS', 'ONGC.NS',
            'TATASTEEL.NS', 'NTPC.NS', 'POWERGRID.NS', 'M&M.NS', 'WIPRO.NS', 'COALINDIA.NS',
            'ZOMATO.NS', 'DLF.NS', 'HAL.NS', 'BEL.NS', 'VBL.NS', 'TRENT.NS', 'SIEMENS.NS'
        ]

nifty_tickers = get_nifty500_tickers()
print(f"✅ Universe Loaded: {len(nifty_tickers)} stocks ready for processing.")

print("--- STEP 3: DEFINING 15 MARKET PARAMETERS ---")

def calculate_15_features(data):
    df = data.copy()

    # --- 1. Volatility (Risk) ---
    df['Volatility'] = df['Close'].pct_change().rolling(20).std()
    df['ATR'] = ta.atr(df['High'], df['Low'], df['Close'], length=14)
    bb = ta.bbands(df['Close'], length=20, std=2)
    if bb is not None:
        df['BB_Width'] = (bb.iloc[:, 2] - bb.iloc[:, 0]) / bb.iloc[:, 1]

    # --- 2. Momentum (Speed) ---
    df['RSI'] = ta.rsi(df['Close'], length=14)
    df['ROC'] = ta.roc(df['Close'], length=10)
    df['WillR'] = ta.willr(df['High'], df['Low'], df['Close'], length=14)
    stoch = ta.stoch(df['High'], df['Low'], df['Close'])
    if stoch is not None: df['Stoch_K'] = stoch.iloc[:, 0]
    df['CCI'] = ta.cci(df['High'], df['Low'], df['Close'], length=20)

    # --- 3. Trend (Direction) ---
    macd = ta.macd(df['Close'])
    if macd is not None: df['MACD'] = macd.iloc[:, 0]
    adx = ta.adx(df['High'], df['Low'], df['Close'], length=14)
    if adx is not None: df['ADX'] = adx.iloc[:, 0]
    df['Dist_SMA50'] = (df['Close'] / ta.sma(df['Close'], length=50)) - 1
    df['Dist_SMA200'] = (df['Close'] / ta.sma(df['Close'], length=200)) - 1

    # Parabolic SAR (Reversal)
    psar = ta.psar(df['High'], df['Low'], df['Close'])
    if psar is not None:
        # Combine long/short columns into one distance metric
        psar_combined = psar.iloc[:, 0].fillna(0) + psar.iloc[:, 1].fillna(0)
        df['Dist_PSAR'] = (df['Close'] - psar_combined) / df['Close']

    # --- 4. Volume (Conviction) ---
    df['MFI'] = ta.mfi(df['High'], df['Low'], df['Close'], df['Volume'], length=14)
    df['CMF'] = ta.cmf(df['High'], df['Low'], df['Close'], df['Volume'], length=20)

    return df.dropna()

print("✅ Feature Engineering Engine Ready.")

print("--- STEP 4: FETCHING TRAINING DATA (INDEX) ---")

# Download Index Data (14 Years)
df_train = yf.download('^NSEI', start='2010-01-01', end='2025-11-28', progress=False)
if isinstance(df_train.columns, pd.MultiIndex): df_train.columns = df_train.columns.get_level_values(0)

# Apply Features
df_train = calculate_15_features(df_train)
print(f"✅ Training Data Loaded: {len(df_train)} days of Market History.")

print("--- STEP 5: TRAINING THE AI MODEL ---")

# 1. Create Targets (The "Truth")
df_train['Future_Ret'] = df_train['Close'].shift(-20) / df_train['Close'] - 1
def label_regime(x):
    if x > 0.025: return 2   # Bull
    elif x < -0.025: return 0 # Bear
    else: return 1            # Sideways
df_train['Target'] = df_train['Future_Ret'].apply(label_regime)

# 2. List the 15 Features used for input
feature_cols = ['Volatility', 'ATR', 'BB_Width', 'RSI', 'ROC', 'WillR', 'Stoch_K', 'CCI',
                'MACD', 'ADX', 'Dist_SMA50', 'Dist_SMA200', 'Dist_PSAR', 'MFI', 'CMF']

# 3. Train Random Forest
# Remove last 20 rows (NaN targets)
train_data = df_train.dropna()
rf_model = RandomForestClassifier(n_estimators=200, min_samples_leaf=5, random_state=42, n_jobs=-1)
rf_model.fit(train_data[feature_cols], train_data['Target'])

print("✅ Model Trained. The AI has learned market patterns.")

print("--- STEP 6: DEFINING STRATEGY LOGIC ---")

class MLRegimeStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        # Read the 'Regime' column which we will generate using the AI
        regime = self.data.Regime[-1]

        if regime == 2: # Bull
            if not self.position:
                self.buy()
        elif regime == 0: # Bear
            if self.position:
                self.position.close()

print("✅ Strategy Logic Defined.")

print("--- STEP 7: RUNNING BACKTEST ON STOCKS ---")

results = []
count = 0

# Running on all stocks. This will take a considerable amount of time.
for ticker in nifty_tickers:
    try:
        # A. Get Data (5 Years)
        data = yf.download(ticker, period="5y", progress=False)
        if isinstance(data.columns, pd.MultiIndex): data.columns = data.columns.get_level_values(0)

        if len(data) < 500: continue # Skip young stocks

        # B. Calculate Indicators
        data = calculate_15_features(data)

        # C. AI Prediction (Vectorized for speed)
        # The AI looks at the 15 features for every row and decides the regime
        pred_input = data[feature_cols]
        data['Regime'] = rf_model.predict(pred_input)

        # D. Run Backtest
        bt = Backtest(data, MLRegimeStrategy, cash=100000, commission=0.002)
        stats = bt.run()

        results.append({
            'Ticker': ticker,
            'Return': stats['Return [%]'],
            'BuyHold': stats['Buy & Hold Return [%]'],
            'WinRate': stats['Win Rate [%]'],
            'Trades': stats['# Trades']
        })
        print(f"✅ {ticker}: {stats['Return [%]']:.1f}%")
        count += 1

    except Exception as e:
        print(f"❌ Error processing {ticker}: {e}")

print(f"✅ Completed testing on {count} stocks.")

print("\n--- STEP 8: PERFORMANCE REPORT ---")

if results:
    df_res = pd.DataFrame(results)
    # Remove infinite values
    df_res = df_res.replace([np.inf, -np.inf], np.nan).dropna()

    print(f"Average Strategy Return: {df_res['Return'].mean():.2f}%")
    print(f"Average Buy & Hold Return: {df_res['BuyHold'].mean():.2f}%")
    print(f"Average Win Rate: {df_res['WinRate'].mean():.2f}%")

    # Show Best Performers
    print("\n🏆 Top 5 AI Performers:")
    print(df_res.sort_values(by='Return', ascending=False).head(5)[['Ticker', 'Return', 'BuyHold']])
else:
    print("No results found.")

print("\n--- STEP 9: STRATEGY ADAPTABILITY CHECK ---")
# We look at the last processed stock to see how often it switched
switches = data['Regime'].diff().abs().sum()
years = len(data) / 252
print(f"Example Ticker: {ticker}")
print(f"Total Regime Switches: {int(switches)}")
print(f"Switches per Year: {switches/years:.1f}")
print("Conclusion: The AI is actively adapting, not just holding.")

print("--- STEP 10: RANDOM STOCK PREDICTOR TOOL ---")

def test_random_stock():
    # 1. Pick Random Stock
    ticker = random.choice(nifty_tickers)
    print(f"\n🎲 Analyzing Random Stock: {ticker}...")

    try:
        # 2. Get Live Data
        data = yf.download(ticker, period="1y", progress=False)
        if isinstance(data.columns, pd.MultiIndex): data.columns = data.columns.get_level_values(0)

        if len(data) < 60:
            print("   Not enough data. Retrying...")
            test_random_stock()
            return

        # 3. Calculate Features
        data = calculate_15_features(data)
        latest_row = data.iloc[-1]

        # 4. Predict
        features = latest_row[feature_cols].values.reshape(1, -1)
        pred = rf_model.predict(features)[0]
        prob = max(rf_model.predict_proba(features)[0]) * 100

        regimes = {0: "🐻 BEARISH (Cash/Sell)", 1: "🦀 SIDEWAYS (Wait)", 2: "🚀 BULLISH (Buy)"}

        # 5. Output
        print(f"---------------------------------------")
        print(f"💰 Price: ₹{latest_row['Close']:.2f}")
        print(f"📊 Regime: {regimes[pred]}")
        print(f"🧠 Confidence: {prob:.2f}%")
        print(f"---------------------------------------")
        print(f"   RSI: {latest_row['RSI']:.2f}")
        print(f"   ADX: {latest_row['ADX']:.2f}")
        print(f"   Vol: {latest_row['Volatility']:.4f}")
        print(f"---------------------------------------")

    except Exception as e:
        print(f"Error: {e}")

# Run the tool
test_random_stock()

import time # Import the time module

print("--- STEP 11: TESTING 5 RANDOM STOCKS ---")
for _ in range(5):
    test_random_stock()
    time.sleep(1) # Pause to be polite to API

