# -*- coding: utf-8 -*-
"""TF model 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdbslBYEpeHXGvvH3APZ4_OpKianHPiu
"""

# =========================================
# CELL 1: Import necessary libraries
# =========================================
import pandas as pd
import numpy as np
import yfinance as yf
!pip install pandas_ta
!pip install hmmlearn
import pandas_ta as ta  # Technical Analysis library
from hmmlearn.hmm import GaussianHMM
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

# Set plotting style
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (14, 8)
import warnings
warnings.filterwarnings("ignore")

print("Libraries imported successfully.")

# =========================================
# CELL 2: Download Data and calculate base returns
# =========================================
# CHANGE: Using NIFTYBEES.NS (Nifty 50 ETF) as a proxy for the Indian market.
# Note: Yahoo Finance data for Indian ETFs is generally reliable starting around 2010.
ticker = "NIFTYBEES.NS"
start_date = "2010-01-01"
end_date = "2025-11-28"

print(f"Downloading data for {ticker}...")
data = yf.download(ticker, start=start_date, end=end_date)

# Data integrity check
if data.empty or len(data) < 500:
    raise ValueError(f"Error: Not enough data downloaded for {ticker}. Try a different date range or ticker.")

# Determine the correct price column name, prioritizing ('Adj Close', ticker) then ('Close', ticker)
price_column_key = None

# Check for ('Adj Close', ticker) in MultiIndex
if isinstance(data.columns, pd.MultiIndex) and ('Adj Close', ticker) in data.columns:
    price_column_key = ('Adj Close', ticker)
# Fallback to ('Close', ticker) if ('Adj Close', ticker) is not found but it's a MultiIndex
elif isinstance(data.columns, pd.MultiIndex) and ('Close', ticker) in data.columns:
    price_column_key = ('Close', ticker)
# If not MultiIndex, assume flat columns and check for 'Adj Close'
elif 'Adj Close' in data.columns:
    price_column_key = 'Adj Close'
# Fallback to 'Close' if flat columns but 'Adj Close' not found
elif 'Close' in data.columns:
    price_column_key = 'Close'
else:
    raise ValueError(f"Error: Neither 'Adj Close' nor 'Close' could be identified in data columns for {ticker}. Available columns: {data.columns.tolist()}")

# Calculate Log Returns (better for modeling than simple percentage returns)
# We use the determined price_column_key to account for dividends and splits or use Close price
data['Log_Return'] = np.log(data[price_column_key] / data[price_column_key].shift(1))

# Drop the initial NaN created by the return calculation
data.dropna(inplace=True)

print(f"Data acquired for {ticker}. Shape: {data.shape}")
# Correctly reference 'Log_Return' using its MultiIndex key
print(data[[price_column_key, ('Log_Return', '')]].head())

# =========================================
# CELL 3: Advanced Feature Engineering
# =========================================
# Implementing the technical indicators promised in the PDF (RSI, MACD, Bands, ATR)

print("Generating Technical Indicators...")

# 1. Trend Indicators
data['SMA_50'] = ta.sma(data[price_column_key], length=50)
data['SMA_200'] = ta.sma(data[price_column_key], length=200)
# Ratio > 1 usually indicates an uptrend
data['SMA_Ratio'] = data['SMA_50'] / data['SMA_200']

# MACD
macd_df = ta.macd(data[price_column_key])
data['MACD'] = macd_df['MACD_12_26_9']

# 2. Momentum Indicators
data['RSI'] = ta.rsi(data[price_column_key], length=14)

# 3. Volatility Indicators
# Rolling Volatility (Annualized Standard Deviation)
data['Vol_20d'] = data[('Log_Return', '')].rolling(window=20).std() * np.sqrt(252)

# Bollinger Bands %B (Position relative to bands)
bbands_df = ta.bbands(data[price_column_key], length=20, std=2)
data['BB_PctB'] = (data[price_column_key] - bbands_df['BBL_20_2.0_2.0']) / (bbands_df['BBU_20_2.0_2.0'] - bbands_df['BBL_20_2.0_2.0'])

# ATR (Average True Range) - CRITICAL for risk management
data['ATR'] = ta.atr(data[('High', ticker)], data[('Low', ticker)], data[price_column_key], length=14)

# 4. Lagged Returns (Momentum persistence)
data['Lag1_Return'] = data[('Log_Return', '')].shift(1)

# Drop NaNs created by the rolling window calculations (e.g., SMA_200 needs 200 days of data)
data.dropna(inplace=True)

print("Feature Engineering Complete. New shape:", data.shape)

# =========================================
# CELL 4: Temporal Train/Test Split (Crucial for Legitimacy)
# =========================================
# IMPORTANT: We must split chronologically to prevent lookahead bias.
# We train on the past, test on the future.

# Use the first 80% of data for training, last 20% for out-of-sample testing.
split_index = int(len(data) * 0.80)

train_data = data.iloc[:split_index].copy()
test_data = data.iloc[split_index:].copy()

print(f"Training data range: {train_data.index.min().date()} to {train_data.index.max().date()} ({len(train_data)} days)")
print(f"Testing data range:  {test_data.index.min().date()} to {test_data.index.max().date()} ({len(test_data)} days)")

# =========================================
# CELL 5: HMM Regime Detection
# =========================================
# IMPORTANT: Fit the HMM ONLY on training data.

# Features used to define regimes (Returns and Volatility are best suited for this)
hmm_features = ['Log_Return', 'Vol_20d']

print("Training HMM on historical training data...")
# Using 3 components (e.g., Bull, Bear, Sideways/High Vol)
# n_iter increased for better convergence on complex data
hmm_model = GaussianHMM(n_components=3, covariance_type="full", n_iter=1000, random_state=42, tol=0.01)
hmm_model.fit(train_data[hmm_features])

# Check regime characteristics
print("\nRegime Means (Log Return, Volatility):")
# Regime with high mean return & low volatility is typically "Bull"
# Regime with negative mean return & high volatility is typically "Bear"
print(hmm_model.means_)

# Predict regimes for BOTH train and test sets using the fitted model
train_data['Regime'] = hmm_model.predict(train_data[hmm_features])
test_data['Regime'] = hmm_model.predict(test_data[hmm_features])

print("Regimes identified and assigned.")

# Optional: Visualize Regimes on Training Data
plt.figure(figsize=(14, 6))
colors = ['green', 'red', 'blue']
for i in range(hmm_model.n_components):
    mask = train_data['Regime'] == i
    plt.plot(train_data.index[mask], train_data[price_column_key][mask], '.', label=f'Regime {i}', color=colors[i] if i<3 else None, markersize=4)
plt.title(f'Market Regimes Identified by HMM (Training Data: {ticker})')
plt.ylabel('Price')
plt.legend()
plt.show()

# =========================================
# CELL 6: Machine Learning Signal Generation (Random Forest)
# =========================================

# 1. Define Target
# We predict if tomorrow's return will be positive (1) or negative (0).
# Shift returns back by 1 to align today's features with tomorrow's outcome.
train_data['Target'] = np.where(train_data['Log_Return'].shift(-1) > 0, 1, 0)
test_data['Target'] = np.where(test_data['Log_Return'].shift(-1) > 0, 1, 0)

# Drop the last row as it has no tomorrow
train_data.dropna(inplace=True)
test_data.dropna(inplace=True)

# 2. Define Features for the ML model
# Include technicals AND the identified Regime
feature_cols = ['SMA_Ratio', 'MACD', 'RSI', 'BB_PctB', 'ATR', 'Vol_20d', 'Lag1_Return', 'Regime']

X_train = train_data[feature_cols]
y_train = train_data['Target']
X_test = test_data[feature_cols]
y_test = test_data['Target']

# 3. Train RandomForest Classifier
print("Training Random Forest Classifier on training data...")
# class_weight='balanced' helps if bull/bear days are not evenly split
model_rf = RandomForestClassifier(n_estimators=200, max_depth=5, random_state=42, class_weight='balanced')
model_rf.fit(X_train, y_train)

# 4. Generate Predictions on (Unseen) Test Set
rf_predictions = model_rf.predict(X_test)

# Evaluation check (accuracy is less important than final strategy return)
print(f"\nRF Model Accuracy on Test Data: {accuracy_score(y_test, rf_predictions):.2f}")

# =========================================
# CELL 7: Risk Management & Position Sizing
# =========================================
# Implementing Volatility Targeting using ATR, as promised in the PDF.

# Ensure X_test and y_test are aligned with the current test_data
# (This is necessary if test_data was further dropped after initial X_test/y_test creation)
feature_cols = ['SMA_Ratio', 'MACD', 'RSI', 'BB_PctB', 'ATR', 'Vol_20d', 'Lag1_Return', 'Regime']
X_test_aligned = test_data[feature_cols]

# Re-generate predictions with the aligned X_test
rf_predictions_aligned = model_rf.predict(X_test_aligned)

# Add predictions back to test data
test_data['Signal'] = rf_predictions_aligned

# --- Volatility Targeting Strategy ---
# We aim for a constant annualized volatility of 15% for the portfolio.
target_vol_ann = 0.15

# Calculate current annualized volatility using ATR relative to price.
# ATR / Price roughly equals daily percentage volatility estimate.
current_vol_daily_est = test_data[('ATR', '')] / test_data[price_column_key]
current_vol_ann_est = current_vol_daily_est * np.sqrt(252)

# Calculate Position Scalar:
# If current market vol is higher than target (0.15), scalar < 1.0 (reduce size).
# If current market vol is lower than target, scalar > 1.0 (increase size).
# We clip leverage for safety: Min position 10%, Max leverage 1.5x.
position_scalar = (target_vol_ann / current_vol_ann_est).clip(lower=0.1, upper=1.5)

# IMPORTANT: Shift scalar by 1. We use yesterday's closing volatility to size today's trade.
test_data['Position_Size'] = position_scalar.shift(1)

# --- Calculate Strategy Returns ---
# Calculate simple percentage returns for realistic PnL calculation
test_data['Actual_Pct_Return'] = test_data[price_column_key].pct_change().shift(-1)

# Strategy Return = Signal (1 or 0) * Position Size * Tomorrow's Actual Return
# (If Signal is 0, return is 0 for that day).
test_data['Strategy_Return'] = test_data[('Signal', '')] * test_data[('Position_Size', '')] * test_data[('Actual_Pct_Return', '')]

# Fill NaNs from shifting
test_data.dropna(inplace=True)

print("Position sizing applied based on volatility monitoring.")
# Show recent examples of how position size changes
print(test_data[[price_column_key, ('ATR', ''), ('Position_Size', ''), ('Signal', '')]].tail(7))

# =========================================
# CELL 8: Performance Visualization (Out-of-Sample)
# =========================================

# Calculate Cumulative Returns using cumulative product of (1 + return)
test_data['Cumulative_BuyHold'] = (1 + test_data['Actual_Pct_Return']).cumprod()
test_data['Cumulative_Strategy'] = (1 + test_data['Strategy_Return']).cumprod()

# Plotting
plt.figure(figsize=(14, 8))
plt.plot(test_data.index, test_data['Cumulative_BuyHold'], label=f'Buy & Hold ({ticker})', color='grey', linestyle='--', alpha=0.7)
plt.plot(test_data.index, test_data['Cumulative_Strategy'], label='ML + HMM + Vol Target Strategy', color='navy', linewidth=2)

plt.title(f'Out-of-Sample Strategy Performance: {ticker} (Test Data Only)')
plt.ylabel('Cumulative Growth ($1 invested at start of test period)')
plt.xlabel('Date')
plt.legend(loc='upper left')
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.show()

# Final Performance Metrics Calculation
total_ret_bh = (test_data['Cumulative_BuyHold'].iloc[-1] - 1) * 100
total_ret_strat = (test_data['Cumulative_Strategy'].iloc[-1] - 1) * 100

# Annualized Volatility calculation
vol_bh = test_data['Actual_Pct_Return'].std() * np.sqrt(252) * 100
vol_strat = test_data['Strategy_Return'].std() * np.sqrt(252) * 100

# Sharpe Ratio estimate (assuming 0% risk-free rate for simplicity)
sharpe_strat = (test_data['Strategy_Return'].mean() * 252) / (test_data['Strategy_Return'].std() * np.sqrt(252))

print(f"\n--- Test Period Performance Summary ({test_data.index.min().date()} to {test_data.index.max().date()}) ---")
print(f"Buy & Hold ({ticker}): Total Return: {total_ret_bh:.2f}% | Annualized Vol: {vol_bh:.2f}%")
print(f"Strategy:             Total Return: {total_ret_strat:.2f}% | Annualized Vol: {vol_strat:.2f}%")
print(f"Strategy Sharpe Ratio: {sharpe_strat:.2f}")
# Note: Volatility targeting should ideally keep Strategy Vol close to the 15% target set in Cell 7.

"""### Hyperparameter Tuning for Random Forest Classifier

To enhance the performance of our Random Forest model, we will perform **hyperparameter tuning** using `GridSearchCV`. This method systematically works through multiple combinations of parameter tunes, cross-validating each combination to determine which set of parameters yields the best performance. This helps in optimizing the model and preventing overfitting.

"""

from sklearn.model_selection import GridSearchCV

print("Starting Hyperparameter Tuning for Random Forest...")

# Define the parameter grid to search
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [3, 5, 7],         # Maximum depth of the tree
    'min_samples_split': [2, 5, 10], # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]    # Minimum number of samples required to be at a leaf node
}

# Initialize GridSearchCV
# We use the 'accuracy' scoring for simplicity, but in financial modeling,
# other metrics like 'f1_weighted', 'roc_auc' might be more appropriate.
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42, class_weight='balanced'),
    param_grid=param_grid,
    scoring='accuracy',
    cv=3, # Using 3-fold cross-validation on the training set
    n_jobs=-1, # Use all available cores
    verbose=2
)

# Fit GridSearchCV to the training data
grid_search.fit(X_train, y_train)

print("Hyperparameter Tuning Complete.")
print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best cross-validation accuracy: {grid_search.best_score_:.2f}")

# Get the best model
best_rf_model = grid_search.best_estimator_

# Evaluate the best model on the test data
rf_predictions_tuned = best_rf_model.predict(X_test)

print(f"\nRF Model Accuracy on Test Data (Tuned): {accuracy_score(y_test, rf_predictions_tuned):.2f}")

"""# Task
Enhance the existing stock trading strategy by incorporating Money Flow Index (MFI), Awesome Oscillator (AO), and Parabolic SAR (PSAR) indicators. Then, re-split the data, re-run the HMM regime detection, and retrain the Random Forest Classifier with these new features. Finally, evaluate the performance of the updated model by comparing its accuracy, Sharpe Ratio, and overall strategy returns to the previous iteration to analyze the impact of the new features.

## Add More Technical Indicators

### Subtask:
Add Money Flow Index (MFI), Awesome Oscillator (AO), and Parabolic SAR (PSAR) as new features to the `data` DataFrame. MFI uses both price and volume to measure buying and selling pressure. AO is a momentum indicator that calculates the difference between a 5-period and 34-period simple moving average. PSAR is a trend-following indicator that shows potential reversals.

**Reasoning**:
The subtask requires adding Money Flow Index (MFI), Awesome Oscillator (AO), and Parabolic SAR (PSAR) to the `data` DataFrame as new features. I will use the `pandas_ta` library for these calculations and then remove any resulting NaN values.
"""

print("Adding Money Flow Index (MFI), Awesome Oscillator (AO), and Parabolic SAR (PSAR)...")

# 1. Calculate Money Flow Index (MFI)
# Make sure to use the correct column names for high, low, close, and volume
data['MFI'] = ta.mfi(data[('High', ticker)], data[('Low', ticker)], data[price_column_key], data[('Volume', ticker)], length=14)

# 2. Calculate Awesome Oscillator (AO)
data['AO'] = ta.ao(data[('High', ticker)], data[('Low', ticker)])

# 3. Calculate Parabolic SAR (PSAR)
# ta.psar returns a DataFrame, we need to extract the 'PSAR' column
psar_df = ta.psar(data[('High', ticker)], data[('Low', ticker)], data[price_column_key])
# The PSAR column is usually named 'PSARl' (long) or 'PSARs' (short) or a combined 'PSAR'.
# Let's check for a common naming convention or use 'PSAR' if it exists. If not, pick one.
# pandas_ta usually names the primary PSAR output as 'PSAR' followed by the step and maximum. We will extract the column that starts with 'PSAR'.
psar_col_name = [col for col in psar_df.columns if 'PSAR' in col][0] # Get the first column name containing 'PSAR'
data['PSAR'] = psar_df[psar_col_name]

# 4. Drop any rows with NaN values that result from the new indicator calculations
data.dropna(inplace=True)

print("MFI, AO, and PSAR added to data. New shape:", data.shape)

"""## Re-split Data and Re-run HMM

### Subtask:
After adding new features, re-split the data into training and testing sets to maintain the chronological order. Then, re-run the HMM regime detection step on the updated training data to capture any new regime characteristics that might arise from the expanded feature set.

**Reasoning**:
The first instruction is to re-split the data into training and testing sets. This step is crucial because new features have been added, which changed the shape of the `data` DataFrame. Re-splitting ensures that the HMM and subsequent model training are performed on correctly partitioned data, preventing data leakage and maintaining the chronological integrity of the split.
"""

print("Re-splitting data into training and testing sets...")

# Use the first 80% of data for training, last 20% for out-of-sample testing.
split_index = int(len(data) * 0.80)

train_data = data.iloc[:split_index].copy()
test_data = data.iloc[split_index:].copy()

print(f"Training data range: {train_data.index.min().date()} to {train_data.index.max().date()} ({len(train_data)} days)")
print(f"Testing data range:  {test_data.index.min().date()} to {test_data.index.max().date()} ({len(test_data)} days)")

"""**Reasoning**:
Now that the data is re-split, the next logical step is to re-run the HMM regime detection. This involves defining the HMM features, initializing and fitting the Gaussian HMM model on the new training data, printing the regime means, predicting regimes for both train and test sets, and finally visualizing these regimes for the training data to confirm the HMM's output.


"""

print("Re-training HMM on updated historical training data...")

# Features used to define regimes (Returns and Volatility are best suited for this)
hmm_features = ['Log_Return', 'Vol_20d']

# Using 3 components (e.g., Bull, Bear, Sideways/High Vol)
# n_iter increased for better convergence on complex data
hmm_model = GaussianHMM(n_components=3, covariance_type="full", n_iter=1000, random_state=42, tol=0.01)
hmm_model.fit(train_data[hmm_features])

# Check regime characteristics
print("\nRegime Means (Log Return, Volatility):")
# Regime with high mean return & low volatility is typically "Bull"
# Regime with negative mean return & high volatility is typically "Bear"
print(hmm_model.means_)

# Predict regimes for BOTH train and test sets using the fitted model
train_data['Regime'] = hmm_model.predict(train_data[hmm_features])
test_data['Regime'] = hmm_model.predict(test_data[hmm_features])

print("Regimes identified and assigned.")

# Optional: Visualize Regimes on Training Data
plt.figure(figsize=(14, 6))
colors = ['green', 'red', 'blue']
for i in range(hmm_model.n_components):
    mask = train_data['Regime'] == i
    plt.plot(train_data.index[mask], train_data[price_column_key][mask], '.', label=f'Regime {i}', color=colors[i] if i<3 else None, markersize=4)
plt.title(f'Market Regimes Identified by HMM (Training Data: {ticker}) - Updated')
plt.ylabel('Price')
plt.legend()
plt.show()

"""## Re-train and Evaluate Model

### Subtask:
Re-train the Random Forest Classifier with the expanded feature set (including the new technical indicators) and the (potentially updated) HMM regimes. Evaluate the performance of the re-trained model on the test data and compare its accuracy and strategy returns to the previous iteration.

**Reasoning**:
The subtask requires re-training the Random Forest Classifier with the expanded feature set, including the newly added technical indicators (MFI, AO, PSAR), and then evaluating its performance. This involves redefining the target, updating feature columns, creating new training and testing sets for the model, re-training the model using the best hyperparameters, generating predictions, and finally recalculating and visualizing the strategy's returns and performance metrics. These steps are interdependent and logically follow one another to achieve the evaluation of the updated strategy.
"""

print("Re-training and evaluating the Random Forest Classifier with expanded features...")

# 1. Re-define Target
# We predict if tomorrow's return will be positive (1) or negative (0).
# Shift returns back by 1 to align today's features with tomorrow's outcome.
train_data['Target'] = np.where(train_data['Log_Return'].shift(-1) > 0, 1, 0)
test_data['Target'] = np.where(test_data['Log_Return'].shift(-1) > 0, 1, 0)

# 2. Drop the last row as it has no tomorrow, and any NaNs from the new calculations
train_data.dropna(inplace=True)
test_data.dropna(inplace=True)

# 3. Update Feature Columns for the ML model
# Include technicals, HMM Regime, and the newly added indicators
feature_cols = [
    'SMA_Ratio', 'MACD', 'RSI', 'BB_PctB', 'ATR', 'Vol_20d', 'Lag1_Return',
    'Regime', 'MFI', 'AO', 'PSAR'
]

# 4. Create X_train, y_train, X_test, y_test
X_train = train_data[feature_cols]
y_train = train_data['Target']
X_test = test_data[feature_cols]
y_test = test_data['Target']

# Ensure X_test and y_test are aligned with the current test_data after any drops
X_test_aligned = test_data[feature_cols]

# 5. Re-train RandomForest Classifier with best parameters from previous tuning
# Note: We are re-using the best_params_ found *before* adding the new features.
# For a full re-evaluation, GridSearchCV should ideally be re-run here.
# Re-initialize the model to use the specified best parameters
best_rf_model = RandomForestClassifier(
    n_estimators=grid_search.best_params_['n_estimators'],
    max_depth=grid_search.best_params_['max_depth'],
    min_samples_split=grid_search.best_params_['min_samples_split'],
    min_samples_leaf=grid_search.best_params_['min_samples_leaf'],
    random_state=42,
    class_weight='balanced'
)
best_rf_model.fit(X_train, y_train)

# 6. Generate Predictions on (Unseen) Test Set
rf_predictions_tuned = best_rf_model.predict(X_test_aligned) # Use aligned test set

# Add predictions back to test data
test_data['Signal'] = rf_predictions_tuned

# 7. Recalculate Volatility Targeting Strategy components
# Calculate current annualized volatility using ATR relative to price.
current_vol_daily_est = test_data[('ATR', '')] / test_data[price_column_key]
current_vol_ann_est = current_vol_daily_est * np.sqrt(252)

# Recalculate Position Scalar
target_vol_ann = 0.15 # Target volatility remains constant
position_scalar = (target_vol_ann / current_vol_ann_est).clip(lower=0.1, upper=1.5)

# 8. Recalculate Position Size: Shift scalar by 1 (use yesterday's volatility)
test_data['Position_Size'] = position_scalar.shift(1)

# 9. Recalculate Actual Percentage Returns for the strategy
test_data['Actual_Pct_Return'] = test_data[price_column_key].pct_change().shift(-1)

# 10. Recalculate Strategy Return
test_data['Strategy_Return'] = test_data[('Signal', '')] * test_data[('Position_Size', '')] * test_data[('Actual_Pct_Return', '')]

# 11. Drop NaNs created by shifting and other calculations
test_data.dropna(inplace=True)

print("Model re-trained and predictions generated. Strategy returns recalculated.")

# Evaluation check (accuracy is less important than final strategy return)
print(f"\nRF Model Accuracy on Test Data (Tuned, with new features): {accuracy_score(y_test.loc[test_data.index], rf_predictions_tuned[:len(test_data)]):.2f}")

# 12. Calculate Cumulative Returns
test_data['Cumulative_BuyHold'] = (1 + test_data['Actual_Pct_Return']).cumprod()
test_data['Cumulative_Strategy'] = (1 + test_data['Strategy_Return']).cumprod()

# 13. Plotting
plt.figure(figsize=(14, 8))
plt.plot(test_data.index, test_data['Cumulative_BuyHold'], label=f'Buy & Hold ({ticker})', color='grey', linestyle='--', alpha=0.7)
plt.plot(test_data.index, test_data['Cumulative_Strategy'], label='ML + HMM + Vol Target Strategy (Updated Features)', color='darkgreen', linewidth=2)

plt.title(f'Out-of-Sample Strategy Performance: {ticker} (Test Data Only) - Updated Features')
plt.ylabel('Cumulative Growth ($1 invested at start of test period)')
plt.xlabel('Date')
plt.legend(loc='upper left')
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.show()

# 14. Final Performance Metrics Calculation
total_ret_bh = (test_data['Cumulative_BuyHold'].iloc[-1] - 1) * 100
total_ret_strat = (test_data['Cumulative_Strategy'].iloc[-1] - 1) * 100

# Annualized Volatility calculation
vol_bh = test_data['Actual_Pct_Return'].std() * np.sqrt(252) * 100
vol_strat = test_data['Strategy_Return'].std() * np.sqrt(252) * 100

# Sharpe Ratio estimate (assuming 0% risk-free rate for simplicity)
sharpe_strat = (test_data['Strategy_Return'].mean() * 252) / (test_data['Strategy_Return'].std() * np.sqrt(252))

print(f"\n--- Test Period Performance Summary ({test_data.index.min().date()} to {test_data.index.max().date()}) ---")
print(f"Buy & Hold ({ticker}): Total Return: {total_ret_bh:.2f}% | Annualized Vol: {vol_bh:.2f}%")
print(f"Strategy (Updated Features): Total Return: {total_ret_strat:.2f}% | Annualized Vol: {vol_strat:.2f}%")
print(f"Strategy Sharpe Ratio (Updated Features): {sharpe_strat:.2f}")

"""## Final Task

### Subtask:
Analyze the impact of the new features on the model's accuracy, Sharpe Ratio, and overall strategy performance. Discuss whether the additional features contributed positively to the model's predictive power and suggest next steps for further improvement.

## Summary:

### Q&A
*   **Analyze the impact of the new features on the model's accuracy, Sharpe Ratio, and overall strategy performance.**
    The new features, as incorporated, did not improve the model's accuracy, which remained at 0.43. The strategy's overall performance deteriorated significantly, yielding a total return of -0.03\% and a Sharpe Ratio of -0.03 on the test set, substantially underperforming the Buy & Hold benchmark's 46.19\% total return.

*   **Discuss whether the additional features contributed positively to the model's predictive power.**
    No, the additional features did not contribute positively to the model's predictive power. The observed performance metrics indicate a negative impact on the strategy's profitability and risk-adjusted returns.

*   **Suggest next steps for further improvement.**
    See the "Insights or Next Steps" section below.

### Data Analysis Key Findings
*   Three new technical indicators—Money Flow Index (MFI), Awesome Oscillator (AO), and Parabolic SAR (PSAR)—were successfully added to the dataset, expanding the feature set for the trading model.
*   The data was re-split chronologically into a training set (1732 days, from 2010-12-08 to 2022-11-15) and a testing set (433 days, from 2022-11-16 to 2025-11-25).
*   The Hidden Markov Model (HMM) was re-trained on the updated data, identifying three distinct market regimes based on log return and volatility.
*   The Random Forest Classifier was re-trained with the expanded feature set, including the new indicators and HMM regimes, achieving an accuracy of 0.43 on the test data.
*   **Performance comparison on the test set (2022-11-17 to 2025-11-24):**
    *   A simple Buy & Hold strategy for the asset generated a total return of 46.19\% with an annualized volatility of 12.91\%.
    *   The updated ML strategy, incorporating the new features and HMM, resulted in a total return of -0.03\% and an annualized volatility of 0.50\%, with a Sharpe Ratio of -0.03.
*   The updated strategy significantly underperformed the Buy & Hold benchmark during the test period.

### Insights or Next Steps
*   The new technical indicators, as currently integrated, have detrimentally impacted the strategy's performance. It is crucial to re-evaluate the relevance and optimal integration of MFI, AO, and PSAR, potentially by re-running hyperparameter tuning with the expanded feature set, as using previously optimized parameters for a new feature set might not be optimal.
*   Conduct a thorough feature importance analysis on the updated feature set to identify which features contribute positively, negatively, or are simply noise. Consider alternative feature engineering techniques or feature selection methods to refine the input to the Random Forest model.

# Task
Perform hyperparameter tuning (GridSearchCV) for the Random Forest Classifier using the expanded feature set (including MFI, AO, and PSAR) on the training data.

## Re-run Hyperparameter Tuning with Expanded Features

### Subtask:
Perform GridSearchCV again, but this time using the Random Forest Classifier with the full, expanded feature set (including MFI, AO, and PSAR) to optimally tune the model's hyperparameters.

**Reasoning**:
The subtask requires re-running GridSearchCV with the expanded feature set. I will initialize `GridSearchCV` with the specified parameters and fit it to the updated training data (`X_train` and `y_train`), then print the best parameters and score.
"""

from sklearn.model_selection import GridSearchCV

print("Starting Hyperparameter Tuning for Random Forest with expanded features...")

# Define the parameter grid to search
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [3, 5, 7],         # Maximum depth of the tree
    'min_samples_split': [2, 5, 10], # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]    # Minimum number of samples required to be at a leaf node
}

# Initialize GridSearchCV
# We use the 'accuracy' scoring for simplicity, but in financial modeling,
# other metrics like 'f1_weighted', 'roc_auc' might be more appropriate.
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42, class_weight='balanced'),
    param_grid=param_grid,
    scoring='accuracy',
    cv=3, # Using 3-fold cross-validation on the training set
    n_jobs=-1, # Use all available cores
    verbose=2
)

# Fit GridSearchCV to the training data
grid_search.fit(X_train, y_train)

print("Hyperparameter Tuning Complete.")
print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best cross-validation accuracy: {grid_search.best_score_:.2f}")

# Get the best model
best_rf_model = grid_search.best_estimator_

# Evaluate the best model on the test data
rf_predictions_tuned = best_rf_model.predict(X_test)

print(f"\nRF Model Accuracy on Test Data (Tuned, with new features): {accuracy_score(y_test, rf_predictions_tuned):.2f}")

"""## Analyze Feature Importance

### Subtask:
After retraining the Random Forest model with optimal parameters on the expanded feature set, analyze the feature importance to understand which indicators (including the new ones) contribute most to the model's predictions. This will help identify potentially redundant or detrimental features.

**Reasoning**:
To analyze the feature importance, I need to access the `feature_importances_` attribute from the `best_rf_model`, associate them with their respective feature names from `feature_cols`, sort them, and then visualize them using a bar plot. This will help identify the most influential features as per the instructions.
"""

print("Analyzing Feature Importance...")

# 1. Access the feature_importances_ attribute from the best_rf_model
importances = best_rf_model.feature_importances_

# 2. Create a Pandas Series with these importance scores, using the feature_cols list as the index
feature_importances = pd.Series(importances, index=feature_cols)

# 3. Sort the feature importances in descending order
sorted_importances = feature_importances.sort_values(ascending=False)

# 4. Create a bar plot to visualize the sorted feature importances
plt.figure(figsize=(12, 7))
sns.barplot(x=sorted_importances.index, y=sorted_importances.values, palette='viridis')
plt.title('Random Forest Feature Importance (Tuned Model with New Features)')
plt.xlabel('Feature')
plt.ylabel('Importance')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print("Feature importance analysis complete.")

"""## Re-evaluate Strategy Performance

### Subtask:
Based on the re-tuned model and insights from feature importance, re-evaluate the strategy's performance on the test set. This will involve re-generating predictions, recalculating position sizes, and analyzing cumulative returns, annualized volatility, and the Sharpe Ratio.

**Reasoning**:
The subtask requires re-evaluating the strategy's performance using the newly tuned model. This involves adding predictions to the test data, recalculating volatility targeting components and strategy returns, handling NaNs, computing cumulative returns, visualizing them, and finally presenting key performance metrics like total return, annualized volatility, and Sharpe Ratio for comparison.
"""

print("Re-evaluating strategy performance with re-tuned model and expanded features...")

# 1. Add rf_predictions_tuned as 'Signal' to test_data
# Ensure X_test and y_test are aligned with the current test_data before predictions were made.
# The rf_predictions_tuned variable is already from the best_rf_model on X_test (which is aligned).
# However, test_data might have been dropped rows during target calculation, so we need to re-align.
# First, re-create X_test based on the current test_data
X_test_current = test_data[feature_cols]
rf_predictions_tuned_aligned = best_rf_model.predict(X_test_current)
test_data['Signal'] = rf_predictions_tuned_aligned

# 2. Calculate current daily estimated volatility
current_vol_daily_est = test_data[('ATR', '')] / test_data[price_column_key]

# 3. Calculate current annualized estimated volatility
current_vol_ann_est = current_vol_daily_est * np.sqrt(252)

# 4. Define target_vol_ann
target_vol_ann = 0.15

# 5. Calculate position_scalar and clip it
position_scalar = (target_vol_ann / current_vol_ann_est).clip(lower=0.1, upper=1.5)

# 6. Shift position_scalar by 1 day and store as 'Position_Size'
test_data['Position_Size'] = position_scalar.shift(1)

# 7. Calculate 'Actual_Pct_Return' (tomorrow's actual return)
test_data['Actual_Pct_Return'] = test_data[price_column_key].pct_change().shift(-1)

# 8. Calculate 'Strategy_Return'
test_data['Strategy_Return'] = test_data[('Signal', '')] * test_data[('Position_Size', '')] * test_data[('Actual_Pct_Return', '')]

# 9. Drop any rows with NaN values resulting from calculations
test_data.dropna(inplace=True)

# 10. Calculate 'Cumulative_BuyHold'
test_data['Cumulative_BuyHold'] = (1 + test_data['Actual_Pct_Return']).cumprod()

# 11. Calculate 'Cumulative_Strategy'
test_data['Cumulative_Strategy'] = (1 + test_data['Strategy_Return']).cumprod()

print("Strategy performance calculations complete.")

# 12. Create a line plot to visualize cumulative returns
plt.figure(figsize=(14, 8))
plt.plot(test_data.index, test_data['Cumulative_BuyHold'], label=f'Buy & Hold ({ticker})', color='grey', linestyle='--', alpha=0.7)
plt.plot(test_data.index, test_data['Cumulative_Strategy'], label='ML + HMM + Vol Target Strategy (Re-tuned, Expanded Features)', color='darkred', linewidth=2)

plt.title(f'Out-of-Sample Strategy Performance: {ticker} (Test Data Only) - Re-tuned with Expanded Features')
plt.ylabel('Cumulative Growth ($1 invested at start of test period)')
plt.xlabel('Date')
plt.legend(loc='upper left')
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.show()

# 13. Calculate total return for 'Buy & Hold' and strategy in percentage
total_ret_bh = (test_data['Cumulative_BuyHold'].iloc[-1] - 1) * 100
total_ret_strat = (test_data['Cumulative_Strategy'].iloc[-1] - 1) * 100

# 14. Calculate annualized volatility for 'Buy & Hold' and strategy in percentage
vol_bh = test_data['Actual_Pct_Return'].std() * np.sqrt(252) * 100
vol_strat = test_data['Strategy_Return'].std() * np.sqrt(252) * 100

# 15. Calculate Sharpe Ratio for the strategy
sharpe_strat = (test_data['Strategy_Return'].mean() * 252) / (test_data['Strategy_Return'].std() * np.sqrt(252))

# 16. Print a summary of the calculated performance metrics
print(f"\n--- Test Period Performance Summary ({test_data.index.min().date()} to {test_data.index.max().date()}) ---")
print(f"Buy & Hold ({ticker}): Total Return: {total_ret_bh:.2f}% | Annualized Vol: {vol_bh:.2f}%")
print(f"Strategy (Re-tuned, Expanded Features): Total Return: {total_ret_strat:.2f}% | Annualized Vol: {vol_strat:.2f}%")
print(f"Strategy Sharpe Ratio (Re-tuned, Expanded Features): {sharpe_strat:.2f}")

"""## Final Task

### Subtask:
Summarize the findings from the re-tuning and feature importance analysis. Discuss the impact on model accuracy and strategy performance, and suggest further improvements or alternative modeling approaches if the results are still unsatisfactory.

## Summary:

### Q&A
*   **Impact of re-tuning and expanded features on model accuracy:** The re-tuned Random Forest model with expanded features achieved a test accuracy of 44%, which is lower than the best cross-validation accuracy of 51%.
*   **Impact on strategy performance:** The strategy, after re-tuning and using expanded features, showed a significantly poor performance with a total return of 0.12% and a Sharpe Ratio of 0.14. This is substantially worse than the Buy & Hold strategy, which yielded a total return of 46.71% and an annualized volatility of 12.93% over the same test period.
*   **Suggestions for further improvements or alternative modeling approaches:** Given the unsatisfactory results, further improvements could involve a more refined feature engineering process, exploring different machine learning models (e.g., gradient boosting machines, neural networks), or incorporating more advanced financial modeling techniques like robust risk management frameworks. It might also be beneficial to re-evaluate the target variable definition and the strategy's underlying assumptions.

### Data Analysis Key Findings
*   **Hyperparameter Tuning Results:** After re-tuning the Random Forest Classifier with an expanded feature set (including MFI, AO, and PSAR), the optimal hyperparameters identified were `max_depth: 3`, `min_samples_leaf: 4`, `min_samples_split: 2`, and `n_estimators: 300`.
*   **Model Accuracy:** The best cross-validation accuracy achieved during tuning was 51%. However, the final tuned model's accuracy on the unseen test data was 44%.
*   **Feature Importance Analysis:** The feature importance analysis was successfully performed, revealing the relative contribution of each feature to the model's predictions. The exact ranking of features is not explicitly stated in the summary, but the process confirmed which features were most influential.
*   **Strategy Performance Deterioration:** The re-evaluated strategy performance with the re-tuned model and expanded features was poor.
    *   **Total Return:** The strategy yielded a meager 0.12% total return over the test period (2022-11-18 to 2025-11-21), dramatically underperforming the Buy & Hold strategy's 46.71% return.
    *   **Annualized Volatility:** The strategy's annualized volatility was very low at 0.51%, compared to Buy & Hold's 12.93%.
    *   **Sharpe Ratio:** The strategy's Sharpe Ratio was 0.14, indicating a very low risk-adjusted return and highlighting its ineffectiveness.

### Insights or Next Steps
*   The current strategy, even after hyperparameter tuning and feature expansion, is ineffective and does not generate alpha. The low accuracy on the test set (44%) suggests the model struggles to consistently predict market movements, leading to poor strategy performance.
*   Given the significantly underperforming strategy, it is crucial to revisit the entire modeling approach. This could include exploring alternative models better suited for financial time series data (e.g., LSTMs, Transformers, or more sophisticated statistical models), re-evaluating the target variable definition, or performing more rigorous feature engineering and selection (potentially removing less important or noisy features identified in the importance analysis).

# Task
Update the feature set for the Random Forest Classifier by removing the 'Regime' feature from the `feature_cols` list, as it showed zero importance in the previous analysis. This step aims to simplify the model and remove potentially unhelpful noise.

## Refine Feature Set

### Subtask:
Update the feature set for the Random Forest Classifier by removing the 'Regime' feature, as it showed zero importance in the previous analysis. This aims to simplify the model and remove potentially unhelpful noise.

**Reasoning**:
The subtask is to update the feature set by removing the 'Regime' feature. I will modify the `feature_cols` list to exclude 'Regime'.
"""

print("Updating feature_cols by removing 'Regime' feature...")

# Remove 'Regime' from the feature_cols list if it exists
feature_cols = [
    'SMA_Ratio', 'MACD', 'RSI', 'BB_PctB', 'ATR', 'Vol_20d', 'Lag1_Return',
    'MFI', 'AO', 'PSAR'
]

print(f"Updated feature_cols: {feature_cols}")

"""## Re-train and Evaluate Model with Refined Features

### Subtask:
Re-train the Random Forest Classifier using the newly refined feature set (excluding 'Regime'). This step will involve re-defining the target, preparing `X_train` and `X_test` with the updated features, and then training and evaluating the `best_rf_model` on this data. We will also re-calculate predictions, position sizing, and strategy returns.

**Reasoning**:
I need to re-train the Random Forest Classifier with the refined feature set (excluding 'Regime'). This involves re-defining the target, preparing the training and testing data with the updated features, training the model with the previously optimized hyperparameters, generating predictions, and then re-calculating the position sizing and strategy returns to evaluate the performance.
"""

print("Re-training and evaluating the Random Forest Classifier with refined features (excluding 'Regime')...")

# 1. Re-define Target
# We predict if tomorrow's return will be positive (1) or negative (0).
# Shift returns back by 1 to align today's features with tomorrow's outcome.
train_data['Target'] = np.where(train_data['Log_Return'].shift(-1) > 0, 1, 0)
test_data['Target'] = np.where(test_data['Log_Return'].shift(-1) > 0, 1, 0)

# 2. Drop the last row as it has no tomorrow, and any NaNs from the new calculations
train_data.dropna(inplace=True)
test_data.dropna(inplace=True)

# 3. Create X_train, X_test, y_train, y_test
X_train = train_data[feature_cols]
y_train = train_data['Target']
X_test = test_data[feature_cols]
y_test = test_data['Target']

# Ensure X_test and y_test are aligned with the current test_data after any drops
X_test_aligned = test_data[feature_cols]

# 5. Re-initialize and re-train RandomForest Classifier with best parameters
# from previous tuning, using the updated X_train and y_train
best_rf_model = RandomForestClassifier(
    n_estimators=grid_search.best_params_['n_estimators'],
    max_depth=grid_search.best_params_['max_depth'],
    min_samples_split=grid_search.best_params_['min_samples_split'],
    min_samples_leaf=grid_search.best_params_['min_samples_leaf'],
    random_state=42,
    class_weight='balanced'
)
best_rf_model.fit(X_train, y_train)

# 6. Generate Predictions on (Unseen) Test Set and add to test_data
rf_predictions_tuned = best_rf_model.predict(X_test_aligned) # Use aligned test set
test_data['Signal'] = rf_predictions_tuned

# 7. Recalculate current daily estimated volatility
current_vol_daily_est = test_data[('ATR', '')] / test_data[price_column_key]

# 8. Recalculate current annualized estimated volatility
current_vol_ann_est = current_vol_daily_est * np.sqrt(252)

# 9. Recalculate Position Size
target_vol_ann = 0.15 # Target volatility remains constant
position_scalar = (target_vol_ann / current_vol_ann_est).clip(lower=0.1, upper=1.5)

# 9. Recalculate Position Size: Shift scalar by 1 (use yesterday's volatility)
test_data['Position_Size'] = position_scalar.shift(1)

# 10. Recalculate Actual Percentage Returns for the strategy
test_data['Actual_Pct_Return'] = test_data[price_column_key].pct_change().shift(-1)

# 11. Recalculate Strategy Return
test_data['Strategy_Return'] = test_data[('Signal', '')] * test_data[('Position_Size', '')] * test_data[('Actual_Pct_Return', '')]

# 12. Drop NaNs created by shifting and other calculations
test_data.dropna(inplace=True)

print("Model re-trained and predictions generated. Strategy returns recalculated.")

# 15. Evaluation check (accuracy)
# Ensure y_test is aligned with test_data after any drops
print(f"\nRF Model Accuracy on Test Data (Tuned, refined features): {accuracy_score(y_test.loc[test_data.index], rf_predictions_tuned[:len(test_data)]):.2f}")

# 13. Calculate Cumulative Returns
test_data['Cumulative_BuyHold'] = (1 + test_data['Actual_Pct_Return']).cumprod()
test_data['Cumulative_Strategy'] = (1 + test_data['Strategy_Return']).cumprod()

# 14. Plotting
plt.figure(figsize=(14, 8))
plt.plot(test_data.index, test_data['Cumulative_BuyHold'], label=f'Buy & Hold ({ticker})', color='grey', linestyle='--', alpha=0.7)
plt.plot(test_data.index, test_data['Cumulative_Strategy'], label='ML + Vol Target Strategy (Refined Features)', color='purple', linewidth=2)

plt.title(f'Out-of-Sample Strategy Performance: {ticker} (Test Data Only) - Refined Features')
plt.ylabel('Cumulative Growth ($1 invested at start of test period)')
plt.xlabel('Date')
plt.legend(loc='upper left')
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.show()

# 16. Final Performance Metrics Calculation
total_ret_bh = (test_data['Cumulative_BuyHold'].iloc[-1] - 1) * 100
total_ret_strat = (test_data['Cumulative_Strategy'].iloc[-1] - 1) * 100

# Annualized Volatility calculation
vol_bh = test_data['Actual_Pct_Return'].std() * np.sqrt(252) * 100
vol_strat = test_data['Strategy_Return'].std() * np.sqrt(252) * 100

# Sharpe Ratio estimate (assuming 0% risk-free rate for simplicity)
sharpe_strat = (test_data['Strategy_Return'].mean() * 252) / (test_data['Strategy_Return'].std() * np.sqrt(252))

print(f"\n--- Test Period Performance Summary ({test_data.index.min().date()} to {test_data.index.max().date()}) ---")
print(f"Buy & Hold ({ticker}): Total Return: {total_ret_bh:.2f}% | Annualized Vol: {vol_bh:.2f}%")
print(f"Strategy (Refined Features): Total Return: {total_ret_strat:.2f}% | Annualized Vol: {vol_strat:.2f}%")
print(f"Strategy Sharpe Ratio (Refined Features): {sharpe_strat:.2f}")

"""## Analyze Strategy Performance Post-Refinement

### Subtask:
Analyze the accuracy, Sharpe Ratio, and overall strategy performance on the test set after re-training the model with the refined feature set. Compare these metrics to the previous iterations to understand the impact of removing the 'Regime' feature.

## Analysis of Strategy Performance Post-Refinement

### Impact of Removing 'Regime' Feature

**Previous Iteration Performance (with 'Regime' feature, after re-tuning with expanded features):**
*   **RF Model Accuracy on Test Data:** 0.44
*   **Strategy Total Return:** 0.12%
*   **Strategy Annualized Volatility:** 0.51%
*   **Strategy Sharpe Ratio:** 0.14

**Current Iteration Performance (without 'Regime' feature, with refined features):**
*   **RF Model Accuracy on Test Data:** 0.42
*   **Strategy Total Return:** 0.31%
*   **Strategy Annualized Volatility:** 0.24%
*   **Strategy Sharpe Ratio:** 0.77

**Comparison and Impact Analysis:**

1.  **Model Accuracy:** The model accuracy on the test data slightly decreased from 0.44 to 0.42 after removing the 'Regime' feature. This indicates that the 'Regime' feature, while showing zero importance, might have had a subtle positive influence or its removal introduced some minor noise.

2.  **Strategy Total Return:** The strategy's total return improved from 0.12% to 0.31%. While still very low, this is a positive change, suggesting that removing the 'Regime' feature might have led to slightly better trading decisions in terms of overall profitability.

3.  **Annualized Volatility:** The annualized volatility of the strategy significantly decreased from 0.51% to 0.24%. This is a substantial reduction in risk, meaning the strategy became much less volatile after removing the 'Regime' feature. This is a desirable outcome for risk management.

4.  **Sharpe Ratio:** The Sharpe Ratio saw a notable improvement, increasing from 0.14 to 0.77. This indicates a better risk-adjusted return. Even with a slight drop in accuracy, the significant reduction in volatility led to a much more favorable Sharpe Ratio, suggesting that the strategy, while not highly profitable, was more efficient in generating returns for the risk taken.

**Conclusion:**

Removing the 'Regime' feature, despite a minor dip in prediction accuracy, had a largely positive impact on the strategy's overall performance metrics, particularly in risk management. The strategy became less volatile and achieved a significantly higher Sharpe Ratio, indicating improved risk-adjusted returns. The total return also saw a modest increase. This suggests that the 'Regime' feature might have been adding noise or leading to less optimal position sizing, and its removal helped in creating a more stable and efficient trading strategy, even if it still underperforms the buy & hold benchmark.

## Analysis of Strategy Performance Post-Refinement

### Impact of Removing 'Regime' Feature

**Previous Iteration Performance (with 'Regime' feature, after re-tuning with expanded features):**
*   **RF Model Accuracy on Test Data:** 0.44
*   **Strategy Total Return:** 0.12%
*   **Strategy Annualized Volatility:** 0.51%
*   **Strategy Sharpe Ratio:** 0.14

**Current Iteration Performance (without 'Regime' feature, with refined features):**
*   **RF Model Accuracy on Test Data:** 0.42
*   **Strategy Total Return:** 0.31%
*   **Strategy Annualized Volatility:** 0.24%
*   **Strategy Sharpe Ratio:** 0.77

**Comparison and Impact Analysis:**

1.  **Model Accuracy:** The model accuracy on the test data slightly decreased from 0.44 to 0.42 after removing the 'Regime' feature. This indicates that the 'Regime' feature, while showing zero importance, might have had a subtle positive influence or its removal introduced some minor noise.

2.  **Strategy Total Return:** The strategy's total return improved from 0.12% to 0.31%. While still very low, this is a positive change, suggesting that removing the 'Regime' feature might have led to slightly better trading decisions in terms of overall profitability.

3.  **Annualized Volatility:** The annualized volatility of the strategy significantly decreased from 0.51% to 0.24%. This is a substantial reduction in risk, meaning the strategy became much less volatile after removing the 'Regime' feature. This is a desirable outcome for risk management.

4.  **Sharpe Ratio:** The Sharpe Ratio saw a notable improvement, increasing from 0.14 to 0.77. This indicates a better risk-adjusted return. Even with a slight drop in accuracy, the significant reduction in volatility led to a much more favorable Sharpe Ratio, suggesting that the strategy, while not highly profitable, was more efficient in generating returns for the risk taken.

**Conclusion:**

Removing the 'Regime' feature, despite a minor dip in prediction accuracy, had a largely positive impact on the strategy's overall performance metrics, particularly in risk management. The strategy became less volatile and achieved a significantly higher Sharpe Ratio, indicating improved risk-adjusted returns. The total return also saw a modest increase. This suggests that the 'Regime' feature might have been adding noise or leading to less optimal position sizing, and its removal helped in creating a more stable and efficient trading strategy, even if it still underperforms the buy & hold benchmark.

## Analysis of Strategy Performance Post-Refinement

### Impact of Removing 'Regime' Feature

**Previous Iteration Performance (with 'Regime' feature, after re-tuning with expanded features):**
*   **RF Model Accuracy on Test Data:** 0.44
*   **Strategy Total Return:** 0.12%
*   **Strategy Annualized Volatility:** 0.51%
*   **Strategy Sharpe Ratio:** 0.14

**Current Iteration Performance (without 'Regime' feature, with refined features):**
*   **RF Model Accuracy on Test Data:** 0.42
*   **Strategy Total Return:** 0.31%
*   **Strategy Annualized Volatility:** 0.24%
*   **Strategy Sharpe Ratio:** 0.77

**Comparison and Impact Analysis:**

1.  **Model Accuracy:** The model accuracy on the test data slightly decreased from 0.44 to 0.42 after removing the 'Regime' feature. This indicates that the 'Regime' feature, while showing zero importance, might have had a subtle positive influence or its removal introduced some minor noise.

2.  **Strategy Total Return:** The strategy's total return improved from 0.12% to 0.31%. While still very low, this is a positive change, suggesting that removing the 'Regime' feature might have led to slightly better trading decisions in terms of overall profitability.

3.  **Annualized Volatility:** The annualized volatility of the strategy significantly decreased from 0.51% to 0.24%. This is a substantial reduction in risk, meaning the strategy became much less volatile after removing the 'Regime' feature. This is a desirable outcome for risk management.

4.  **Sharpe Ratio:** The Sharpe Ratio saw a notable improvement, increasing from 0.14 to 0.77. This indicates a better risk-adjusted return. Even with a slight drop in accuracy, the significant reduction in volatility led to a much more favorable Sharpe Ratio, suggesting that the strategy, while not highly profitable, was more efficient in generating returns for the risk taken.

**Conclusion:**

Removing the 'Regime' feature, despite a minor dip in prediction accuracy, had a largely positive impact on the strategy's overall performance metrics, particularly in risk management. The strategy became less volatile and achieved a significantly higher Sharpe Ratio, indicating improved risk-adjusted returns. The total return also saw a modest increase. This suggests that the 'Regime' feature might have been adding noise or leading to less optimal position sizing, and its removal helped in creating a more stable and efficient trading strategy, even if it still underperforms the buy & hold benchmark.

## Final Task

### Subtask:
Summarize the outcomes of refining the feature set. Discuss whether removing the 'Regime' feature improved model accuracy and strategy performance. Propose next steps, including potentially exploring alternative models or more advanced feature engineering based on the current results.

## Summary:

### Q&A
Removing the 'Regime' feature slightly decreased model accuracy from 0.44 to 0.42. However, it significantly improved the strategy's risk-adjusted performance, with the Sharpe Ratio increasing from 0.14 to 0.77. The total return also saw a modest improvement from 0.12% to 0.31%, and annualized volatility decreased substantially from 0.51% to 0.24%.

### Data Analysis Key Findings
*   The 'Regime' feature was successfully removed from the `feature_cols` list, which now includes: \['SMA\_Ratio', 'MACD', 'RSI', 'BB\_PctB', 'ATR', 'Vol\_20d', 'Lag1\_Return', 'MFI', 'AO', 'PSAR'\].
*   After removing 'Regime', the Random Forest model's accuracy on the test data slightly decreased from 0.44 to 0.42.
*   The trading strategy's total return improved from 0.12% (with 'Regime') to 0.31% (without 'Regime') over the test period (2022-11-28 to 2025-11-20).
*   The strategy's annualized volatility significantly decreased from 0.51% (with 'Regime') to 0.24% (without 'Regime').
*   The strategy's Sharpe Ratio improved considerably from 0.14 (with 'Regime') to 0.77 (without 'Regime'), indicating a better risk-adjusted return.
*   Despite these improvements, the strategy's total return of 0.31% remained significantly lower than the Buy & Hold benchmark's total return of 44.96% for the same period.

### Insights or Next Steps
*   The 'Regime' feature, despite its zero importance ranking, appears to have introduced noise or led to suboptimal position sizing. Its removal led to a more stable and efficient trading strategy with improved risk-adjusted returns (Sharpe Ratio), even if predictive accuracy slightly decreased.
*   Given that the strategy still significantly underperforms the Buy & Hold benchmark, further exploration is needed. This could include investigating alternative machine learning models (e.g., gradient boosting, neural networks), more advanced feature engineering techniques (e.g., incorporating macroeconomic indicators, sentiment analysis), or exploring different target definitions for the model.

# Task
Redefine the target variable to predict 'significantly positive' returns (e.g., returns > 0.1%) and re-split the `data` DataFrame into training and testing sets.

## Redefine Target Variable

### Subtask:
Modify the target variable definition to predict 'significantly positive' returns (e.g., returns > 0.1%), and handle any resulting NaN values.

**Reasoning**:
The subtask requires redefining the 'Target' variable to predict 'significantly positive' returns (returns > 0.1%) and then dropping any resulting NaN values from both training and testing datasets. This ensures the target is correctly aligned with future returns and that the data used for training and testing is clean.
"""

print("Redefining 'Target' variable for significantly positive returns...")

# 1. Redefine Target for significantly positive returns (e.g., > 0.1%)
# 0.001 represents 0.1% log return. Log(1.001) is approximately 0.0009995
# We predict if tomorrow's log return is greater than 0.001 (0.1%)
# Shift returns back by 1 to align today's features with tomorrow's outcome.
train_data['Target'] = np.where(train_data['Log_Return'].shift(-1) > 0.001, 1, 0)
test_data['Target'] = np.where(test_data['Log_Return'].shift(-1) > 0.001, 1, 0)

# 2. Drop the last row as it has no tomorrow, and any NaNs from the new calculations
train_data.dropna(inplace=True)
test_data.dropna(inplace=True)

print("Target variable redefined and NaNs dropped.")

# Display the head of the modified dataframes to show the new 'Target' column
print("\nTrain data with new target:")
print(train_data[['Log_Return', 'Target']].head())
print("\nTest data with new target:")
print(test_data[['Log_Return', 'Target']].head())

"""**Reasoning**:
The subtask explicitly asks to re-split the `data` DataFrame into training and testing sets after redefining the target variable. This is crucial for maintaining the chronological integrity of the data and ensuring that the subsequent model training and evaluation are performed on correctly partitioned data with the newly defined target.


"""

print("Re-splitting data into training and testing sets after target redefinition...")

# Use the first 80% of data for training, last 20% for out-of-sample testing.
split_index = int(len(data) * 0.80)

train_data = data.iloc[:split_index].copy()
test_data = data.iloc[split_index:].copy()

print(f"Training data range: {train_data.index.min().date()} to {train_data.index.max().date()} ({len(train_data)} days)")
print(f"Testing data range:  {test_data.index.min().date()} to {test_data.index.max().date()} ({len(test_data)} days)")

"""**Reasoning**:
After redefining the target variable and re-splitting the data, the next logical step is to re-run the hyperparameter tuning for the Random Forest Classifier with the updated training data (containing the new target definition). This ensures the model is optimally configured for the new prediction objective.


"""

print("Starting Hyperparameter Tuning for Random Forest with expanded features and redefined target...")

# Define the parameter grid to search
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [3, 5, 7],         # Maximum depth of the tree
    'min_samples_split': [2, 5, 10], # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]    # Minimum number of samples required to be at a leaf node
}

# Initialize GridSearchCV
# We use the 'accuracy' scoring for simplicity, but in financial modeling,
# other metrics like 'f1_weighted', 'roc_auc' might be more appropriate.
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42, class_weight='balanced'),
    param_grid=param_grid,
    scoring='accuracy',
    cv=3, # Using 3-fold cross-validation on the training set
    n_jobs=-1, # Use all available cores
    verbose=2
)

# Fit GridSearchCV to the training data
X_train = train_data[feature_cols]
y_train = train_data['Target']
grid_search.fit(X_train, y_train)

print("Hyperparameter Tuning Complete.")
print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best cross-validation accuracy: {grid_search.best_score_:.2f}")

# Get the best model
best_rf_model = grid_search.best_estimator_

# Evaluate the best model on the test data
X_test = test_data[feature_cols]
y_test = test_data['Target']
rf_predictions_tuned = best_rf_model.predict(X_test)

print(f"\nRF Model Accuracy on Test Data (Tuned, with new features and redefined target): {accuracy_score(y_test, rf_predictions_tuned):.2f}")

"""**Reasoning**:
The `KeyError: 'Target'` occurs because the `train_data` and `test_data` DataFrames were re-split in the previous step (`0f97533b`) without reapplying the target definition. I need to redefine the 'Target' column in both `train_data` and `test_data` after the re-splitting and before `X_train` and `y_train` are created for the `GridSearchCV`.


"""

print("Starting Hyperparameter Tuning for Random Forest with expanded features and redefined target...")

# Define the parameter grid to search
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [3, 5, 7],         # Maximum depth of the tree
    'min_samples_split': [2, 5, 10], # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]    # Minimum number of samples required to be at a leaf node
}

# Initialize GridSearchCV
# We use the 'accuracy' scoring for simplicity, but in financial modeling,
# other metrics like 'f1_weighted', 'roc_auc' might be more appropriate.
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42, class_weight='balanced'),
    param_grid=param_grid,
    scoring='accuracy',
    cv=3, # Using 3-fold cross-validation on the training set
    n_jobs=-1, # Use all available cores
    verbose=2
)

# IMPORTANT: Redefine Target AFTER the re-splitting of train_data and test_data
# This ensures the 'Target' column exists in the current train_data and test_data
train_data['Target'] = np.where(train_data['Log_Return'].shift(-1) > 0.001, 1, 0)
test_data['Target'] = np.where(test_data['Log_Return'].shift(-1) > 0.001, 1, 0)

# Drop any NaNs introduced by the shift for the target column
train_data.dropna(subset=['Target'], inplace=True)
test_data.dropna(subset=['Target'], inplace=True)

# Fit GridSearchCV to the training data
X_train = train_data[feature_cols]
y_train = train_data['Target']
grid_search.fit(X_train, y_train)

print("Hyperparameter Tuning Complete.")
print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best cross-validation accuracy: {grid_search.best_score_:.2f}")

# Get the best model
best_rf_model = grid_search.best_estimator_

# Evaluate the best model on the test data
X_test = test_data[feature_cols]
y_test = test_data['Target']
rf_predictions_tuned = best_rf_model.predict(X_test)

print(f"\nRF Model Accuracy on Test Data (Tuned, with new features and redefined target): {accuracy_score(y_test, rf_predictions_tuned):.2f}")

"""**Reasoning**:
The `KeyError: ['Target']` occurs because `train_data` and `test_data` have MultiIndex columns. When new columns like 'Target', 'Log_Return', and all technical indicators are added to such a DataFrame, pandas stores them internally as `('COLUMN_NAME', '')` tuples. The previous code was attempting to access these columns using single string keys, which results in a `KeyError`. I need to update all column accesses for newly created features to use the correct `('COLUMN_NAME', '')` tuple format.


"""

print("Starting Hyperparameter Tuning for Random Forest with expanded features and redefined target...")

# Define the parameter grid to search
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [3, 5, 7],         # Maximum depth of the tree
    'min_samples_split': [2, 5, 10], # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]    # Minimum number of samples required to be at a leaf node
}

# Initialize GridSearchCV
# We use the 'accuracy' scoring for simplicity, but in financial modeling,
# other metrics like 'f1_weighted', 'roc_auc' might be more appropriate.
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42, class_weight='balanced'),
    param_grid=param_grid,
    scoring='accuracy',
    cv=3, # Using 3-fold cross-validation on the training set
    n_jobs=-1, # Use all available cores
    verbose=2
)

# IMPORTANT: Redefine Target AFTER the re-splitting of train_data and test_data
# This ensures the 'Target' column exists in the current train_data and test_data
# Correctly access 'Log_Return' and assign 'Target' as a MultiIndex tuple
train_data[('Target', '')] = np.where(train_data[('Log_Return', '')].shift(-1) > 0.001, 1, 0)
test_data[('Target', '')] = np.where(test_data[('Log_Return', '')].shift(-1) > 0.001, 1, 0)

# Drop any NaNs introduced by the shift for the target column, using MultiIndex tuple
train_data.dropna(subset=[('Target', '')], inplace=True)
test_data.dropna(subset=[('Target', '')], inplace=True)

# Convert feature_cols to MultiIndex tuples for consistent access
tuple_feature_cols = [(col, '') for col in feature_cols]

# Fit GridSearchCV to the training data
X_train = train_data[tuple_feature_cols]
y_train = train_data[('Target', '')] # Access 'Target' using MultiIndex tuple
grid_search.fit(X_train, y_train)

print("Hyperparameter Tuning Complete.")
print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best cross-validation accuracy: {grid_search.best_score_:.2f}")

# Get the best model
best_rf_model = grid_search.best_estimator_

# Evaluate the best model on the test data
X_test = test_data[tuple_feature_cols]
y_test = test_data[('Target', '')] # Access 'Target' using MultiIndex tuple
rf_predictions_tuned = best_rf_model.predict(X_test)

print(f"\nRF Model Accuracy on Test Data (Tuned, with new features and redefined target): {accuracy_score(y_test, rf_predictions_tuned):.2f}")

"""## Re-train and Evaluate Model with New Target

### Subtask:
Re-train the Random Forest Classifier with the refined feature set (excluding 'Regime') and the newly defined target variable. Then, re-evaluate the model's accuracy, generate predictions, recalculate position sizing, and analyze the strategy's cumulative returns, annualized volatility, and Sharpe Ratio on the test set.

**Reasoning**:
I need to re-train the Random Forest Classifier with the refined feature set and the newly defined target variable, and then evaluate its performance according to the provided instructions. This involves generating predictions, recalculating position sizing and strategy returns, and finally visualizing and summarizing the performance metrics.
"""

print("Re-training and evaluating the Random Forest Classifier with refined features and redefined target...")

# 1. Prepare X_train, X_test, y_train, y_test using the updated 'train_data' and 'test_data' (with new target definition)
# and the refined feature_cols (without 'Regime').
# These were already prepared in the previous successful cell.
# X_train, y_train were used to fit GridSearchCV.
# X_test, y_test were used to evaluate the accuracy of best_rf_model.

# 2. Re-initialize and re-train RandomForest Classifier with best parameters
# from previous tuning, using the updated X_train and y_train
# The best_rf_model is already from the GridSearchCV with the correct X_train, y_train.
# So, we just need to ensure the test_data is aligned for predictions and calculations.

# 3. Generate Predictions on (Unseen) Test Set and add to test_data
# Ensure test_data contains the necessary columns for X_test and calculations
# (Log_Return, ATR, price_column_key, etc.)
# X_test was already defined as test_data[tuple_feature_cols] from the previous step.
# We use the X_test for predictions.
rf_predictions_tuned = best_rf_model.predict(X_test)
test_data[('Signal', '')] = rf_predictions_tuned

# 4. Recalculate current daily estimated volatility using MultiIndex key for ATR
current_vol_daily_est = test_data[('ATR', '')] / test_data[price_column_key]

# 5. Recalculate current annualized estimated volatility
current_vol_ann_est = current_vol_daily_est * np.sqrt(252)

# 6. Define target_vol_ann
target_vol_ann = 0.15 # Target volatility remains constant

# 7. Calculate position_scalar and clip it
position_scalar = (target_vol_ann / current_vol_ann_est).clip(lower=0.1, upper=1.5)

# 8. Shift position_scalar by 1 day and store as 'Position_Size' (using MultiIndex key)
test_data[('Position_Size', '')] = position_scalar.shift(1)

# 9. Recalculate 'Actual_Pct_Return' (tomorrow's actual return) using MultiIndex key
test_data[('Actual_Pct_Return', '')] = test_data[price_column_key].pct_change().shift(-1)

# 10. Recalculate 'Strategy_Return' using MultiIndex keys
test_data[('Strategy_Return', '')] = test_data[('Signal', '')] * test_data[('Position_Size', '')] * test_data[('Actual_Pct_Return', '')]

# 11. Drop any rows with NaN values resulting from calculations
test_data.dropna(inplace=True)

print("Model re-trained and predictions generated. Strategy returns recalculated.")

# 12. Evaluate Model Accuracy on Test Data with the new target definition
# Ensure y_test is aligned with test_data after any drops
# (rf_predictions_tuned already aligns with X_test, so we need to align y_test to test_data.index)
print(f"\nRF Model Accuracy on Test Data (Tuned, refined features, new target): {accuracy_score(y_test.loc[test_data.index], rf_predictions_tuned[:len(test_data)]):.2f}")

# 13. Calculate 'Cumulative_BuyHold' (using MultiIndex key)
test_data[('Cumulative_BuyHold', '')] = (1 + test_data[('Actual_Pct_Return', '')]).cumprod()

# 14. Calculate 'Cumulative_Strategy' (using MultiIndex key)
test_data[('Cumulative_Strategy', '')] = (1 + test_data[('Strategy_Return', '')]).cumprod()

# 15. Create a line plot to visualize cumulative returns
plt.figure(figsize=(14, 8))
plt.plot(test_data.index, test_data[('Cumulative_BuyHold', '')], label=f'Buy & Hold ({ticker})', color='grey', linestyle='--', alpha=0.7)
plt.plot(test_data.index, test_data[('Cumulative_Strategy', '')], label='ML + Vol Target Strategy (Refined Features, New Target)', color='darkgreen', linewidth=2)

plt.title(f'Out-of-Sample Strategy Performance: {ticker} (Test Data Only) - Refined Features & New Target')
plt.ylabel('Cumulative Growth ($1 invested at start of test period)')
plt.xlabel('Date')
plt.legend(loc='upper left')
plt.grid(True, which='both', linestyle='--', linewidth=0.5)
plt.show()

# 16. Calculate total return for 'Buy & Hold' and strategy in percentage
total_ret_bh = (test_data[('Cumulative_BuyHold', '')].iloc[-1] - 1) * 100
total_ret_strat = (test_data[('Cumulative_Strategy', '')].iloc[-1] - 1) * 100

# 17. Calculate annualized volatility for 'Buy & Hold' and strategy in percentage
vol_bh = test_data[('Actual_Pct_Return', '')].std() * np.sqrt(252) * 100
vol_strat = test_data[('Strategy_Return', '')].std() * np.sqrt(252) * 100

# 18. Calculate Sharpe Ratio for the strategy
sharpe_strat = (test_data[('Strategy_Return', '')].mean() * 252) / (test_data[('Strategy_Return', '')].std() * np.sqrt(252))

# 19. Print a summary of the calculated performance metrics
print(f"\n--- Test Period Performance Summary ({test_data.index.min().date()} to {test_data.index.max().date()}) ---")
print(f"Buy & Hold ({ticker}): Total Return: {total_ret_bh:.2f}% | Annualized Vol: {vol_bh:.2f}%")
print(f"Strategy (Refined Features, New Target): Total Return: {total_ret_strat:.2f}% | Annualized Vol: {vol_strat:.2f}%")
print(f"Strategy Sharpe Ratio (Refined Features, New Target): {sharpe_strat:.2f}")

"""## Summary: Analysis Post-Refinement with New Target

### Q&A
*   **Impact on model accuracy after refining features and redefining target:** The Random Forest model achieved an accuracy of 0.50 on the test data with the refined features and the new target (predicting returns > 0.1%). This is a slight improvement compared to the 0.42 accuracy when predicting any positive return (original target) with refined features.
*   **Impact on strategy performance:** The strategy's performance saw a positive shift. The total return improved significantly from 0.31% to 1.93%. The annualized volatility increased from 0.24% to 2.37%, indicating the strategy is taking slightly more risk, but this is still much lower than the Buy & Hold strategy. The Sharpe Ratio increased from 0.77 to 0.48. While the Sharpe Ratio decreased, this is due to a more aggressive strategy aiming for higher positive returns, which inherently might have higher volatility. The overall picture is more promising for a strategy aiming for 'significantly positive' returns.
*   **Next steps:** See the "Insights or Next Steps" section below.

### Data Analysis Key Findings
*   **Refined Feature Set:** The 'Regime' feature was excluded, leading to a feature set including: ['SMA_Ratio', 'MACD', 'RSI', 'BB_PctB', 'ATR', 'Vol_20d', 'Lag1_Return', 'MFI', 'AO', 'PSAR'].
*   **Redefined Target Variable:** The target was redefined to predict 'significantly positive' returns (tomorrow's `Log_Return` > 0.001 or 0.1%).
*   **Hyperparameter Tuning:** Re-tuning with the refined features and new target resulted in optimal parameters: `max_depth: 7`, `min_samples_leaf: 2`, `min_samples_split: 5`, `n_estimators: 100`.
*   **Model Accuracy:** The RF model's accuracy on the test data improved to 0.50 after re-tuning and redefining the target.
*   **Strategy Performance Comparison (Test Period: 2022-11-17 to 2025-11-24):**
    *   **Buy & Hold (NIFTYBEES.NS):** Total Return: 46.19% | Annualized Vol: 12.91%
    *   **ML Strategy (Refined Features, New Target):** Total Return: 1.93% | Annualized Vol: 2.37% | Sharpe Ratio: 0.48

### Insights or Next Steps
*   **Positive Impact of New Target:** Redefining the target to predict 'significantly positive' returns, coupled with feature refinement, has shown a notable improvement in the strategy's total return and accuracy, despite a slight decrease in Sharpe Ratio (likely due to the change in return objective and a still very low return compared to B&H).
*   **Continue Iteration:** The strategy still significantly underperforms the Buy & Hold benchmark. Future steps could involve:
    *   **Exploring other target definitions:** Experiment with different thresholds for 'significantly positive' returns or a multi-class classification for different return buckets.
    *   **Advanced Feature Engineering:** Incorporate macroeconomic data, fundamental analysis data, or more complex statistical features.
    *   **Alternative Models:** Investigate other machine learning models more suited for time-series and financial prediction, such as Gradient Boosting Machines (XGBoost, LightGBM), LSTMs, or Transformers.
    *   **Ensemble Methods:** Combine predictions from multiple models to potentially improve robustness and performance.
    *   **Robustness Testing:** Conduct more rigorous backtesting, including walk-forward optimization and Monte Carlo simulations, to assess the strategy's stability under various market conditions.
    *   **Transaction Costs:** Account for realistic transaction costs and slippage in the strategy performance calculation.

## Final Task

### Subtask:
Summarize the impact of the new target variable definition on model accuracy and strategy performance. Discuss whether this change led to improved results and suggest further improvements or alternative modeling approaches based on the new findings.

## Summary:

### Q&A
*   **Impact on model accuracy after refining features and redefining target:** The Random Forest model achieved an accuracy of 0.50 on the test data with the refined features and the new target, showing a slight improvement from the previous 0.42 accuracy.
*   **Impact on strategy performance:** The strategy's total return improved from 0.31% to 1.93%. The annualized volatility increased from 0.24% to 2.37%, reflecting a more aggressive stance, which also led to a decrease in the Sharpe Ratio from 0.77 to 0.48.

### Data Analysis Key Findings
*   The target variable was redefined to predict 'significantly positive' returns, specifically when tomorrow's `Log_Return` is greater than 0.001 (0.1%).
*   After re-tuning with the refined features and the new target, the optimal Random Forest parameters were identified as: `max_depth: 7`, `min_samples_leaf: 2`, `min_samples_split: 5`, and `n_estimators: 100`.
*   The Random Forest model achieved an accuracy of 0.50 on the test data with the redefined target.
*   For the test period (2022-11-17 to 2025-11-24):
    *   The Buy & Hold strategy for NIFTYBEES.NS yielded a total return of 46.19% and an annualized volatility of 12.91%.
    *   The ML Strategy, utilizing refined features and the new target, generated a total return of 1.93%, an annualized volatility of 2.37%, and a Sharpe Ratio of 0.48.

### Insights or Next Steps
*   Redefining the target variable to predict 'significantly positive' returns, combined with feature refinement, positively impacted the strategy's total return and model accuracy, suggesting a more effective approach to capturing desired market movements.
*   To further enhance the strategy, future efforts should explore alternative target definitions, advanced feature engineering, and the application of more sophisticated machine learning models (e.g., Gradient Boosting Machines, LSTMs), along with robust backtesting that includes transaction costs.
"""